import { SoundCloudTrack } from "@/app/api/soundcloud/types";
export const trackDatabase: SoundCloudTrack[] = [
  {
    id: "1612887819",
    title: "Cardigan -  Taylor Swift (Slowed & Reverb)  Underwater",
    permalinkUrl: "https://soundcloud.com/firas-dido-339455119/cardigan-taylor-swift-slowed",
    artworkUrl: "https://i1.sndcdn.com/artworks-000608199201-6j0j0o-t500x500.jpg",
    duration: 82469,
  },
  {
    id: "215764028",
    title: "Blank Space- taylor swift",
    permalinkUrl: "https://soundcloud.com/h-m-h-m-d-4/blank-space-by-taylor-swift",
    artworkUrl: "https://i1.sndcdn.com/artworks-000100000000-6j0j0o-t500x500.jpg",
    duration: 232040,
  },
  {
    id: "204740608",
    title: "Bad Blood - Taylor Swift - Cover By Ali Brustofski",
    permalinkUrl: "https://soundcloud.com/alibrustofski/bad-blood-taylor-swift-cover-by-ali-brustofski",
    duration: 203381,
  },
  {
    id: "1500507064",
    title: "taylor swift - style (disco lines remix)",
    permalinkUrl: "https://soundcloud.com/discolines/taylor-swift-style-disco-lines-remix",
    duration: 181447,
  },
  {
    id: "1529676697",
    title: "Enchanted - Taylor Swift",
    permalinkUrl: "https://soundcloud.com/hyuraaa/enchanted-taylor-swift",
    duration: 334472,
  },
  {
    id: "301161123",
    title: "Shape of You",
    permalinkUrl: "https://soundcloud.com/edsheeran/shape-of-you",
    duration: 233744,
  },
  {
    id: "213950659",
    title: "Photograph",
    permalinkUrl: "https://soundcloud.com/edsheeran/photograph",
    duration: 259030,
  },
  {
    id: "1118084470",
    title: "Shivers",
    permalinkUrl: "https://soundcloud.com/edsheeran/ed-sheeran-shivers",
    duration: 207882,
  },
  {
    id: "1071204931",
    title: "Bad Habits",
    permalinkUrl: "https://soundcloud.com/edsheeran/ed-sheeran-bad-habits",
    duration: 230792,
  },
  {
    id: "302738496",
    title: "Ed Sheeran & Sia - Shape of You / The Greatest / Cheap Thrills",
    permalinkUrl: "https://soundcloud.com/antwan-atef/ed-sheeran-sia-shape-of-you-the-greatest-cheap-thrills",
    duration: 236063,
  },
  {
    id: "301161119",
    title: "Castle on the Hill",
    permalinkUrl: "https://soundcloud.com/edsheeran/castle-on-the-hill",
    duration: 261198,
  },
  {
    id: "310640631",
    title: "Ed Sheeran - Perfect (Joshua Perez Cover)",
    permalinkUrl: "https://soundcloud.com/user-79781816/ed-sheeran-perfect-official-audio",
    duration: 265271,
  },
  {
    id: "45108181",
    title: "Ed Sheeran - The A Team",
    permalinkUrl: "https://soundcloud.com/wmb/ed-sheeran-the-a-team",
    duration: 261245,
  },
  {
    id: "301653699",
    title: "Ed Sheeran - Shape Of You (James Carter x Levi Remix)",
    permalinkUrl: "https://soundcloud.com/jamescarterpresents/shape-of-you",
    duration: 208580,
  },
  {
    id: "1300244338",
    title: "For My Hand (feat. Ed Sheeran)",
    permalinkUrl: "https://soundcloud.com/burnaboy/for-my-hand-feat-ed-sheeran",
    duration: 159164,
  },
  {
    id: "1258110820",
    title: "WAIT FOR U (feat. Drake & Tems)",
    permalinkUrl: "https://soundcloud.com/futureisnow/future-feat-drake-tems-wait",
    duration: 189936,
  },
  {
    id: "2033868592",
    title: "NOKIA",
    permalinkUrl: "https://soundcloud.com/octobersveryown/nokia",
    duration: 241058,
  },
  {
    id: "2011181635",
    title: "she will - lil wayne feat. drake (instrumental tiktok edit)",
    permalinkUrl: "https://soundcloud.com/aksinnia/she-will-drake-instrumental",
    duration: 120085,
  },
  {
    id: "739466311",
    title: "Life Is Good (feat. Drake)",
    permalinkUrl: "https://soundcloud.com/futureisnow/life-is-good-feat-drake",
    duration: 237767,
  },
  {
    id: "1195988677",
    title: "P power (feat. Drake)",
    permalinkUrl: "https://soundcloud.com/gunna/pussy-power-feat-drake",
    duration: 193384,
  },
  {
    id: "2033868400",
    title: "GIMME A HUG",
    permalinkUrl: "https://soundcloud.com/octobersveryown/gimme-a-hug",
    duration: 193097,
  },
  {
    id: "396615804",
    title: 'BlocBoy JB "LOOK ALIVE" ft. Drake',
    permalinkUrl: "https://soundcloud.com/octobersveryown/blocboy-jb-look-alive-ft-drake",
    duration: 181385,
  },
  {
    id: "2033868136",
    title: "SMALL TOWN FAME",
    permalinkUrl: "https://soundcloud.com/octobersveryown/small-town-fame",
    duration: 148558,
  },
  {
    id: "1887335358",
    title: "Guess featuring billie eilish",
    permalinkUrl: "https://soundcloud.com/charlixcx/guess-featuring-billie-eilish",
    duration: 143360,
  },
  {
    id: "1883862957",
    title: "WILDFLOWER by billie eilish live from amazon musics song line",
    permalinkUrl: "https://soundcloud.com/daughter-of-cain-610198696/wildflower-by-billie-eilish",
    duration: 290482,
  },
  {
    id: "1925063828",
    title: "Timeless - Playboi Carti X The Weeknd (Elias Version) (With OG Outro Adlibs)",
    permalinkUrl:
      "https://soundcloud.com/wanng3343/timeless-playboi-carti-x-the-weeknd-elias-version-with-og-outro-adlibs",
    duration: 285074,
  },
  {
    id: "239485245",
    title: "Future + The Weeknd- Low Life [Prod. By Metro Boomin & Ben Billions]",
    permalinkUrl: "https://soundcloud.com/metroboomin/future-the-weeknd-low-life-prod-by-metro-boomin-ben-billions",
    duration: 313159,
  },
];
